services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: weather
      DB_SYNC: true

      # public for testing purposes
      OPEN_WEATHER_MAP_API_KEY: c09873e716b2b3b712d4245498cea4ee
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "8000:80"